"""Shared constants for the Resemblio API."""

DEFAULT_EXTRACTION_CENTS = 500
ONBOARDING_GRANT_CENTS = 1000
ROTATION_GRACE_HOURS = 48
RATE_LIMIT_PER_MIN = 60
RATE_LIMIT_PER_DAY = 5000
RATE_LIMIT_MIN_WINDOW_SECONDS = 60
RATE_LIMIT_DAY_WINDOW_SECONDS = 86_400
API_KEY_RANDOM_BYTES = 32
API_KEY_TOKEN_LENGTH = 43
API_KEY_PREFIX_HEAD = 8
API_KEY_PREFIX_TAIL = 4
MIN_KEY_PEPPER_CHARS = 32
DOWNLOAD_URL_TTL_SECONDS = 900
R2_BUCKET_NAME = "resemblio-extractions"
DEFAULT_API_SCOPE = "extract"
SCHEMA_V1 = 1

